// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipdb.proto

package go_micro_srv_puffin_ipdb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d3908884966e38, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type Response struct {
	IpInfo               string   `protobuf:"bytes,1,opt,name=ipInfo,proto3" json:"ipInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d3908884966e38, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIpInfo() string {
	if m != nil {
		return m.IpInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.puffin.ipdb.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.puffin.ipdb.Response")
}

func init() { proto.RegisterFile("ipdb.proto", fileDescriptor_53d3908884966e38) }

var fileDescriptor_53d3908884966e38 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2c, 0x48, 0x49,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x48, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca,
	0xd7, 0x2b, 0x2e, 0x2a, 0xd3, 0x2b, 0x28, 0x4d, 0x4b, 0xcb, 0xcc, 0xd3, 0x03, 0xc9, 0x2b, 0x49,
	0x72, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x71, 0x31, 0x65, 0x16, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0x16, 0x28, 0x29, 0x71, 0x71, 0x04, 0xa5, 0x16,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x65, 0x16, 0x78, 0xe6, 0xa5, 0xe5, 0x43,
	0xe5, 0xa1, 0x3c, 0xa3, 0x18, 0x2e, 0x16, 0xcf, 0x02, 0x97, 0x24, 0xa1, 0x10, 0x2e, 0x4e, 0xf7,
	0xd4, 0x12, 0x4f, 0xb0, 0xa0, 0x90, 0xa2, 0x1e, 0x2e, 0xeb, 0xf4, 0xa0, 0x76, 0x49, 0x29, 0xe1,
	0x53, 0x02, 0xb1, 0x53, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x7a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x31, 0x84, 0x8c, 0xe0, 0xcb, 0x00, 0x00, 0x00,
}
